schoolmis/apps/authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from apps.authentication import views
from schoolmis.decorators import anonymous_required

from .views import (
    TeacherCreateView,
    TeacherListView,
    TeacherDetailView,
    TeacherUpdateView,
    TeacherDeleteView,
    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,
    ParentCreateView,
    ParentListView,
    ParentDetailView,
    ParentUpdateView,
    ParentDeleteView,
    ParentAutocomplete,
    export_parent,
    export_student,
    export_teacher,

    )

urlpatterns = [	
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^login/$', anonymous_required(auth_views.login), {'template_name': 'registration/signin.html'},
        name='login'),

    url(r'^teacher-create/$', TeacherCreateView.as_view(), name='teacher_create'),
    url(r'^teacher-list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher-detail/(?P<slug>[\w-]+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^teacher-update/(?P<slug>[\w-]+)/$', TeacherUpdateView.as_view(), name='teacher_update'),
    url(r'^teacher-delete/(?P<slug>[\w-]+)/$', TeacherDeleteView.as_view(), name='teacher_delete'),

    url(r'^student-create/$', StudentCreateView.as_view(), name='student_create'),
    url(r'^student-list/$', StudentListView.as_view(), name='student_list'),
    url(r'^student-detail/(?P<slug>[\w-]+)/$', StudentDetailView.as_view(), name='student_detail'),
    url(r'^student-update/(?P<slug>[\w-]+)/$', StudentUpdateView.as_view(), name='student_update'),
    url(r'^student-delete/(?P<slug>[\w-]+)/$', StudentDeleteView.as_view(), name='student_delete'),

    url(r'^parent-create/$', ParentCreateView.as_view(), name='parent_create'),
    url(r'^parent-list/$', ParentListView.as_view(), name='parent_list'),
    url(r'^parent-detail/(?P<slug>[\w-]+)/$', ParentDetailView.as_view(), name='parent_detail'),
    url(r'^parent-update/(?P<slug>[\w-]+)/$', ParentUpdateView.as_view(), name='parent_update'),
    url(r'^parent-delete/(?P<slug>[\w-]+)/$', ParentDeleteView.as_view(), name='parent_delete'),
    url(r'^parent-autocomplete/$', ParentAutocomplete.as_view(), name='parent_autocomplete'),
    url(r'^export-parent/$', export_parent, name='export-parent'),
    url(r'^export-student/(?P<slug>[\w-]+)/$', export_student, name='export-student'),
    url(r'^export-teacher/$', export_teacher, name='export-teacher'),

]

schoolmis/apps/school/urls.py
from django.conf.urls import url
from apps.school import views

urlpatterns = [

    url(r'^grade-create/$', views.GradeSubjectSectionCreateView.as_view(), name='grade_create'),
    url(r'^grade-list/$', views.GradeListView.as_view(), name='grade_list'),
    url(r'^grade-update/(?P<slug>[\w-]+)/$', views.GradeSubjectSectionUpdateView.as_view(), name='grade_update'),
    url(r'^grade-detail/(?P<slug>[\w-]+)/$', views.GradeDetailView.as_view(), name='grade_detail'),
    url(r'^grade-delete/(?P<slug>[\w-]+)/$', views.GradeDeleteView.as_view(), name='grade_delete'),

    url(r'^exam-type-create/$', views.ExamTypeCreateView.as_view(), name='exam_type_create'),
    url(r'^exam-type-list/$', views.ExamTypeListView.as_view(), name='exam_type_list'),
    url(r'^exam-type-update/(?P<pk>\d+)/$', views.ExamTypeUpdateView.as_view(), name='exam_type_update'),
    url(r'^exam-type-delete/(?P<pk>\d+)/$', views.ExamTypeDeleteView.as_view(), name='exam_type_delete'),

]

schoolmis/schoolmis/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^api/home/', include('apps.home.api.urls', namespace='home-api')),
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('apps.authentication.urls', namespace='authentication')),
    url(r'^reportcard/', include('apps.reportcard.urls', namespace='reportcard')),
    url(r'^school/', include('apps.school.urls', namespace='school')),
    url(r'^note-assignment/', include('apps.notes.urls', namespace='note_assignment')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard'))
]

urlpatterns.append(url(r'^$', TemplateView.as_view(template_name='index.html')),)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "GRS User Admin"
admin.site.site_title = "GRS User Admin Portal"
admin.site.index_title = "GRS Site administration"

schoolmis/apps/school/models.py
from django.db import models
from apps.users.models import TeacherProfile
from django.utils.text import slugify


class ExamType(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_examtype', 'View ExamType'),

        )


class Grade(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        permissions = (
            ('view_grade', 'View Grade'),
            ('detail_grade', 'Detail Grade'),

        )

    def __str__(self):
        return self.name

    def get_section(self):
        return "section: {}".format(self.section_set.all().values('name', 'class_teacher__user__first_name'))

    def get_subjects(self):
        return "subjects: {}".format(self.subject_grade.all().values('name', 'code', 'teacher__user__first_name'))

    def get_students(self):
        return "students: {}".format(self.student_grade.all())


class Section(models.Model):
    name = models.CharField(max_length=15, default='A')
    grade = models.ForeignKey(Grade)
    class_teacher = models.ForeignKey(TeacherProfile, related_name='class_teacher', on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('view_section', 'View Section'),
        )

    def __str__(self):
        return self.name

schoolmis/apps/school/forms.py
from django import forms
from django.forms import inlineformset_factory

from apps.reportcard.models import Subject
from .models import Section, Grade, ExamType


class GradeSubjectForm(forms.ModelForm):

    class Meta:
        model = Subject
        fields = '__all__'


class GradeSectionForm(forms.ModelForm):
    class Meta:
        model = Section
        exclude = ()


GradeSectionFormSet = inlineformset_factory(Grade, Section,
                                            form=GradeSectionForm, extra=1)

GradeSubjectFormSet = inlineformset_factory(Grade, Subject,
                                            form=GradeSubjectForm, extra=1)


class ExamTypeForm(forms.ModelForm):

    class Meta:
        model = ExamType
        fields = '__all__'

schoolmis/apps/school/views.py
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.db import transaction
from django.core.exceptions import PermissionDenied
from django.http import Http404

from apps.userrole.permissions import CheckPermissionCreateMixin, CheckPermissionListMixin, CheckPermissionUpdateMixin, \
    CheckPermissionDeleteMixin, CheckPermissionDetailMixin
from .forms import GradeSectionFormSet, GradeSubjectFormSet, ExamTypeForm
from .mixins import GradeMixin, ExamTypeMixin
from .models import Grade


class GradeSubjectSectionCreateView(GradeMixin, CheckPermissionCreateMixin, CreateView):

    def get_context_data(self, **kwargs):
        data = super(GradeSubjectSectionCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['grade_section'] = GradeSectionFormSet(self.request.POST)
            data['grade_subject'] = GradeSubjectFormSet(self.request.POST)

        else:
            data['grade_section'] = GradeSectionFormSet()
            data['grade_subject'] = GradeSubjectFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        grade_section = context['grade_section']
        grade_subject = context['grade_subject']

        with transaction.atomic():
            self.object = form.save()
            if grade_section.is_valid() and grade_subject.is_valid():
                grade_section.instance = self.object
                grade_subject.instance = self.object
                grade_section.save()
                grade_subject.save()
        return super(GradeSubjectSectionCreateView, self).form_valid(form)


class GradeListView(CheckPermissionListMixin, GradeMixin, ListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.groups.filter(name='Student'):
            context['grade'] = Grade.objects.filter(name=self.request.user.student_profile.grade)
            return context
        elif self.request.user.groups.filter(name='Admin Assistant') | self.request.user.groups.filter(name='Principal'):
            try:
                context['grade'] = Grade.objects.all()
                return context
            except TypeError:
                pass
        elif self.request.user.groups.filter(name='Teacher'):
            try:
                context['grade'] = Grade.objects.filter(name__in=self.request.user.teacher_profile.subject_teacher.
                                                        values('grade__name'))
                return context
            except TypeError:
                pass

        else:
            context['grade'] = None
            return context


class GradeDetailView(CheckPermissionDetailMixin, GradeMixin, DetailView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.groups.filter(name='Student'):
            try:
                grade = Grade.objects.filter(name=self.request.user.student_profile.grade)
                context['grade'] = self.get_object(grade)
                return context
            except Http404:
                raise PermissionDenied
        elif self.request.user.groups.filter(name='Teacher'):
            try:
                grade = Grade.objects.filter(
                    name__in=self.request.user.teacher_profile.subject_teacher.values('grade__name'))
                context['grade'] = self.get_object(grade)

                return context
            except TypeError:
                pass
        elif self.request.user.groups.filter(name='Admin Assistant') or self.request.user.groups.filter(
                name='Principal'):
            context['grade'] = self.get_object()
            return context
        else:
            context['grade'] = None
            return context


class GradeSubjectSectionUpdateView(GradeMixin, CheckPermissionUpdateMixin, UpdateView):

    def get_context_data(self, **kwargs):
        data = super(GradeSubjectSectionUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['grade_section'] = GradeSectionFormSet(self.request.POST, instance=self.object)
            data['grade_subject'] = GradeSubjectFormSet(self.request.POST, instance=self.object)

        else:
            data['grade_section'] = GradeSectionFormSet(instance=self.object)
            data['grade_subject'] = GradeSubjectFormSet(instance=self.object)

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        grade_section = context['grade_section']
        grade_subject = context['grade_subject']

        with transaction.atomic():
            self.object = form.save()

            if grade_section.is_valid() and grade_subject.is_valid():
                grade_section.instance = self.object
                grade_subject.instance = self.object

                grade_section.save()
                grade_subject.save()
        return super(GradeSubjectSectionUpdateView, self).form_valid(form)


class GradeDeleteView(GradeMixin, CheckPermissionDeleteMixin, DeleteView):
    template_name = 'school/grade_delete.html'


class ExamTypeCreateView(ExamTypeMixin, CheckPermissionCreateMixin, CreateView):
    pass


class ExamTypeListView(ExamTypeMixin, CheckPermissionListMixin, ListView):
    pass


class ExamTypeUpdateView(ExamTypeMixin, CheckPermissionUpdateMixin, UpdateView):
    pass


class ExamTypeDeleteView(ExamTypeMixin, CheckPermissionDeleteMixin, DeleteView):
    template_name = 'school/examtype_delete.html'

schoolmis/apps/school/templates/school/examtype_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}

    Sure you want to delete {{exam_type}} ?
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/school/templates/school/examtype_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    
    {{form.as_p}}
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/school/templates/school/examtype_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%  for exam_type in exam_type %}
{{forloop.counter}}. {{exam_type}}
    <a href="{% url 'school:exam_type_update' exam_type.pk%}">Edit </a>
    <a href="{% url 'school:exam_type_delete' exam_type.pk%}">Delete </a>
<br>
{% endfor %}
    <a href="url 'school:exam_type_create' %}' ">Create Exam Type </a>
</body>
</html>

schoolmis/apps/school/templates/school/grade_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">    {% csrf_token %}

    Are you sure you want to delete {{grade}}?
    <input type="submit"/>
</form>
</body>
</html>

schoolmis/apps/school/templates/school/grade_detail.html
 {% load staticfiles %}
{% load filter_groups %}
{% include 'dashboard/base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
 <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
            <div class="logo">
                    GRS 
                </a>
                <span class="label bg-info">Academic Year: ( 2018 - 2019 )</span>
            </div>
            <div class="sidebar-wrapper">
              {% include 'dashboard/sidebar/grade_sidebar.html' %}
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        {% if request.user|has_group:"Student" %}
                            <p>You are login as Student</p>
                        {% elif request.user|has_group:"Teacher" %}
                            <p>You are login as Teacher</p>
                        {% elif request.user|has_group:"Guardian" %}
                            <p>You are login as Guardian</p>
                        {% else %}
                            <p>You are login as Admin Assistant</p>

                        {% endif %}
                        <p class="navbar-brand" >Welcome {{request.user}}</p>
                        <p class="navbar-brand" >
                            {% if request.user|has_group:"Student" %}
                                 Grade 
                                 {{grade}} 
                            {% endif %}
                        </p>

                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right"> 
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                   <i class="fa fa-bars" style="color: #9c27b0;"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Profile</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'authentication:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group  is-empty">
                                <input type="text" class="form-control" placeholder="Search">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <div class="content">           
            <div class="active tab-pane" id="notes">
                <div class="row">
             <div class="col-md-5">
                 <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title">Grade: {{grade}}&nbsp;&nbsp;Section</h4>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <th>ID</th>
                                <th>Section Name </th>
                                <th>Class Teacher</th>
                                <th></th>
                            </thead>
                            {% for section in grade.section_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{section.name}}</td>
                                <td> {{section.class_teacher}} 
                                 
                            </tr>
                            {% endfor %}
                              </tbody>
                                  </table>
                        </div>
                    </div>
                </div>
                  </div>
                    </div>
                    </div>
                    </div>
                    </div>
                        <div class="col-md-7">
                        <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title">Grade:{{grade}}&nbsp;&nbsp;Subjects</h4>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <th>ID</th>
                                <th>Subject Name</th>
                                <th>Subject Code</th>
                                <th>Subject Teacher</th>
                                <th></th>
                            </thead>
                            {% for subject in grade.subject_grade.all %}

                            <tr> 
                                <td>{{ forloop.counter }}</td>
                                <td>{{subject.name}}</td>
                                <td> {{subject.code}} </td>
                                <td> {{subject.teacher}} </td>
                                
                            </tr>
                            {% endfor %} 
                              </tbody>
                                  </table>
                        </div>
                    </div>
                </div>
                 </div>
                        </div>
                    </div>
                </div>
                </div> 
            </div>
            {% if request.user|has_group:"Teacher" or request.user|has_group:"Admin Assistant" or request.user|has_group:"Principal" %}
            <div class="row">
             <div class="col-md-12">
              <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title">Grade:{{grade}}&nbsp;&nbsp;Students-Total: {{ grade.student_grade.all.count }}</h4>
                        <a href = "{% url 'authentication:export-student' grade.slug %}" title="Export to excel"><i class="fa fa-download fa-2x" aria-hidden="true" style="float: right; color:white; margin-top: -30px;left: 10px;"></i></a>
                    </div>
                    <div class="card-content table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <th>ID</th>
                                <th>First Name </th>
                                <th>last Name </th>
                                <th>Student Roll No</th>
                                <th>Student Phone No</th>
                                <th>Parent Name</th>
                                <th>Parent Email</th>
                                <th>Parent Phone No</th>
                            </thead>
                            {% for student in grade.student_grade.all|dictsort:"get_full_name" %}
                            <tr>                            
                                <td>{{ forloop.counter }}</td>
                                {% if request.user|has_group:"Admin Assistant" %}
                                
                                <td><a href="{% url 'authentication:student_update'  student.slug %}" class="marksheet">{{student.first_name}}</a></td>
                                <td><a href="{% url 'authentication:student_update'  student.slug %}" class="marksheet"> {{student.last_name}}</a></td> 
                            </a>
                            {% else %}
                            <td>{{student.first_name}}</td>
                            <td> {{student.last_name}}</td>
                            {% endif %}
                            <td>  {{student.roll_no}}</td>
                            <td> {{student.phone}}</td>

                            <td>{{ student.parent }}</td>

                            <td>  {{student.parent.email}}</td>
                            <td> {{student.parent.phone}}</td>
                            </tr>
                            {% endfor %} 
                                  </table>
                        </div>
                    </div>
                </div>
                  </div>
                    </div>
                    </div>
                    </div>
                    </div>
                    {% endif %}
        </div>
                        </div>
            </body>
<!--   Core JS Files   -->
{% include 'dashboard/dashboardjs.html' %}
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js' %}
        demo.initDashboardPageCharts();

    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

schoolmis/apps/school/templates/school/grade_list.html
{% load filter_groups %}
<div class="col-md-12">
    <div class="card card-plain">
        <div class="card-header" data-background-color="purple">
     {% if request.user|has_group:"Admin Assistant" or request.user|has_group:"Student" or request.user|has_group:"Teacher" or request.user|has_group:"Principal" %}

            <h4 class="title">Grade Lists</h4>
        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                {% if grade %}
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th></th>
                    <th></th>
                </thead>
                {% endif %}

                     {% for grade in grade %}

                    <tr>
                        <td>{{ forloop.counter }}</td>
                        {% if perms.school.detail_grade %}
                        <td><a href="{% url 'school:grade_detail' grade.slug %}"  class="marksheet">Grade:{{grade}}</a></td>
                        {% endif %}
                        {% if perms.school.change_grade %}

                        <td><a href="{% url 'school:grade_update' grade.slug %}" class="marksheets" title="Edit"><i class="fa fa-edit " aria-hidden="true"></i></a>
                            {% endif %}
                        </td>
                        {% if perms.school.delete_grade %}
                        <td><a href="{% url 'school:grade_delete' grade.slug %}" class="marksheets" title="Delete"><i class="fa fa-trash-o " aria-hidden="true"></i></a></td>
                         {% endif %}


                    </tr>
                    {% empty %}
                        Sorry No grade
                        {% endfor %}
                {% endif %}
     
     </tbody>
                      </table>
            </div>
        </div>
    </div>