schoolmis/apps/authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from apps.authentication import views
from schoolmis.decorators import anonymous_required

from .views import (
    TeacherCreateView,
    TeacherListView,
    TeacherDetailView,
    TeacherUpdateView,
    TeacherDeleteView,
    StudentCreateView,
    StudentListView,
    StudentDetailView,
    StudentUpdateView,
    StudentDeleteView,
    ParentCreateView,
    ParentListView,
    ParentDetailView,
    ParentUpdateView,
    ParentDeleteView,
    ParentAutocomplete,
    export_parent,
    export_student,
    export_teacher,

    )

urlpatterns = [	
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^login/$', anonymous_required(auth_views.login), {'template_name': 'registration/signin.html'},
        name='login'),

    url(r'^teacher-create/$', TeacherCreateView.as_view(), name='teacher_create'),
    url(r'^teacher-list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher-detail/(?P<slug>[\w-]+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^teacher-update/(?P<slug>[\w-]+)/$', TeacherUpdateView.as_view(), name='teacher_update'),
    url(r'^teacher-delete/(?P<slug>[\w-]+)/$', TeacherDeleteView.as_view(), name='teacher_delete'),

    url(r'^student-create/$', StudentCreateView.as_view(), name='student_create'),
    url(r'^student-list/$', StudentListView.as_view(), name='student_list'),
    url(r'^student-detail/(?P<slug>[\w-]+)/$', StudentDetailView.as_view(), name='student_detail'),
    url(r'^student-update/(?P<slug>[\w-]+)/$', StudentUpdateView.as_view(), name='student_update'),
    url(r'^student-delete/(?P<slug>[\w-]+)/$', StudentDeleteView.as_view(), name='student_delete'),

    url(r'^parent-create/$', ParentCreateView.as_view(), name='parent_create'),
    url(r'^parent-list/$', ParentListView.as_view(), name='parent_list'),
    url(r'^parent-detail/(?P<slug>[\w-]+)/$', ParentDetailView.as_view(), name='parent_detail'),
    url(r'^parent-update/(?P<slug>[\w-]+)/$', ParentUpdateView.as_view(), name='parent_update'),
    url(r'^parent-delete/(?P<slug>[\w-]+)/$', ParentDeleteView.as_view(), name='parent_delete'),
    url(r'^parent-autocomplete/$', ParentAutocomplete.as_view(), name='parent_autocomplete'),
    url(r'^export-parent/$', export_parent, name='export-parent'),
    url(r'^export-student/(?P<slug>[\w-]+)/$', export_student, name='export-student'),
    url(r'^export-teacher/$', export_teacher, name='export-teacher'),

]

schoolmis/apps/dashboard/urls.py
from django.conf.urls import url

from apps.dashboard.views import Dashboard

urlpatterns = [
    url(r'^$', Dashboard.as_view(), name='dashboard'),

]

schoolmis/apps/home/urls.py
from django.conf.urls import url, include

from apps.home import views
urlpatterns = [
    url(r'^school-create/$', views.SchoolCreateView.as_view(), name='school_create'),
    url(r'^school-list/$', views.SchoolListView.as_view(), name='school_list'),
    url(r'^school-update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='school_update'),
    url(r'^school-delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='school_delete'),

    url(r'^testimonial-create/$', views.TestimonialCreateView.as_view(), name='testimonial_create'),
    url(r'^testimonial-list/$', views.TestimonialListView.as_view(), name='testimonial_list'),
    url(r'^testimonial-update/(?P<pk>\d+)/$', views.TestimonialUpdateView.as_view(), name='testimonial_update'),
    url(r'^testimonial-delete/(?P<pk>\d+)/$', views.TestimonialDeleteView.as_view(), name='testimonial_delete'),

    url(r'^event-create/$', views.EventCreateView.as_view(), name='event_create'),
    url(r'^event-list/$', views.EventListView.as_view(), name='event_list'),
    url(r'^event-detail/(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
    url(r'^event-update/(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_update'),
    url(r'^event-delete/(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),

    url(r'^notice-create/$', views.NoticeCreateView.as_view(), name='notice_create'),
    url(r'^notice-list/$', views.NoticeListView.as_view(), name='notice_list'),
    url(r'^notice-detail/(?P<pk>\d+)/$', views.NoticeDetailView.as_view(), name='notice_detail'),
    url(r'^notice-update/(?P<pk>\d+)/$', views.NoticeUpdateView.as_view(), name='notice_update'),
    url(r'^notice-delete/(?P<pk>\d+)/$', views.NoticeDeleteView.as_view(), name='notice_delete'),

]

schoolmis/apps/notes/urls.py
from django.conf.urls import url
from .views import (
    NoteCreateView,
    NoteListView,
    NoteDetailView,
    NoteUpdateView,
    NoteDeleteView,
    AssignmentCreateView,
    AssignmentListView,
    AssignmentDetailView,
    AssignmentUpdateView,
    AssignmentDeleteView,
    load_students_subjects,
    load_students_subjects_formset,
    load_subjects,
    load_students,



)
urlpatterns = [

    url(r'^note-create/$', NoteCreateView.as_view(), name='note_create'),
    url(r'^note-list/$', NoteListView.as_view(), name='note_list'),
    url(r'^note-detail/(?P<pk>\d+)/$', NoteDetailView.as_view(), name='note_detail'),
    url(r'^note-update/(?P<pk>\d+)/$', NoteUpdateView.as_view(), name='note_update'),
    url(r'^note-delete/(?P<pk>\d+)/$', NoteDeleteView.as_view(), name='note_delete'),

    url(r'^assignment-create/$', AssignmentCreateView.as_view(), name='assignment_create'),
    url(r'^assignment-list/$', AssignmentListView.as_view(), name='assignment_list'),
    url(r'^assignment-detail/(?P<pk>\d+)/$', AssignmentDetailView.as_view(), name='assignment_detail'),
    url(r'^assignment-update/(?P<pk>\d+)/$', AssignmentUpdateView.as_view(), name='assignment_update'),
    url(r'^assignment-delete/(?P<pk>\d+)/$', AssignmentDeleteView.as_view(), name='assignment_delete'),
    url('ajax/load-students-subjects/', load_students_subjects, name='ajax_load_students_subjects'),
    url('ajax/load-students-subjects-formset/', load_students_subjects_formset, name='ajax_load_students_subjects_formset'),
    url('ajax/load-subjects/', load_subjects, name='ajax_load_subjects'),
    url('ajax/load-students/', load_students, name='ajax_load_students'),

]

schoolmis/apps/reportcard/urls.py
from django.conf.urls import url
from .views import (
    SubjectListView,
    AttendanceCreateView,
    AttendanceListView,
    AttendanceDetailView,
    AttendanceUpdateView,
    AttendanceDeleteView,
    MarkSheetCreateView,
    MarkSheetListView,
    MarkSheetDetailView,
    MarkSheetUpdateView,
    MarkSheetDeleteView,
    MarkSheetPdfZipView,
    MarkSheetPdfView,
    StudentMarksCreateView,
    StudentMarksListView,
    StudentMarksDetailView,
    StudentMarksUpdateView,
    StudentMarksDeleteView,
    StudentAutocomplete,


)

urlpatterns = [
    url(r'^subject-list/$', SubjectListView.as_view(), name='subject_list'),

    url(r'^attendance-create/$', AttendanceCreateView.as_view(), name='attendance_create'),
    url(r'^attendance-list/$', AttendanceListView.as_view(), name='attendance_list'),
    url(r'^attendance-detail/(?P<pk>\d+)/$', AttendanceDetailView.as_view(), name='attendance_detail'),
    url(r'^attendance-update/(?P<pk>\d+)/$', AttendanceUpdateView.as_view(), name='attendance_update'),
    url(r'^attendance-delete/(?P<pk>\d+)/$', AttendanceDeleteView.as_view(), name='attendance_delete'),

    url(r'^marksheet-create/$', MarkSheetCreateView.as_view(), name='marksheet_create'),
    url(r'^marksheet-list/$', MarkSheetListView.as_view(), name='marksheet_list'),
    url(r'^marksheet-detail/(?P<pk>\d+)/$', MarkSheetDetailView.as_view(), name='marksheet_detail'),
    url(r'^marksheet-update/(?P<pk>\d+)/$', MarkSheetUpdateView.as_view(), name='marksheet_update'),
    url(r'^marksheet-delete/(?P<pk>\d+)/$', MarkSheetDeleteView.as_view(), name='marksheet_delete'),
    url(r'^marksheet-zip/$', MarkSheetPdfZipView.as_view(), name='marksheet_zip'),
    url(r'^marksheet-pdf/(?P<pk>\d+)/$', MarkSheetPdfView.as_view(), name='marksheet_pdf'),
    url(r'^student-autocomplete/$', StudentAutocomplete.as_view(), name='student_autocomplete'),

    url(r'^mark-create/$', StudentMarksCreateView.as_view(), name='mark_create'),
    url(r'^mark-list/$', StudentMarksListView.as_view(), name='mark_list'),
    url(r'^mark-detail/(?P<pk>\d+)/$', StudentMarksDetailView.as_view(), name='mark_detail'),
    url(r'^mark-update/(?P<pk>\d+)/$', StudentMarksUpdateView.as_view(), name='mark_update'),
    url(r'^mark-delete/(?P<pk>\d+)/$', StudentMarksDeleteView.as_view(), name='mark_delete'),

]

schoolmis/apps/school/urls.py
from django.conf.urls import url
from apps.school import views

urlpatterns = [

    url(r'^grade-create/$', views.GradeSubjectSectionCreateView.as_view(), name='grade_create'),
    url(r'^grade-list/$', views.GradeListView.as_view(), name='grade_list'),
    url(r'^grade-update/(?P<slug>[\w-]+)/$', views.GradeSubjectSectionUpdateView.as_view(), name='grade_update'),
    url(r'^grade-detail/(?P<slug>[\w-]+)/$', views.GradeDetailView.as_view(), name='grade_detail'),
    url(r'^grade-delete/(?P<slug>[\w-]+)/$', views.GradeDeleteView.as_view(), name='grade_delete'),

    url(r'^exam-type-create/$', views.ExamTypeCreateView.as_view(), name='exam_type_create'),
    url(r'^exam-type-list/$', views.ExamTypeListView.as_view(), name='exam_type_list'),
    url(r'^exam-type-update/(?P<pk>\d+)/$', views.ExamTypeUpdateView.as_view(), name='exam_type_update'),
    url(r'^exam-type-delete/(?P<pk>\d+)/$', views.ExamTypeDeleteView.as_view(), name='exam_type_delete'),

]

schoolmis/schoolmis/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^api/home/', include('apps.home.api.urls', namespace='home-api')),
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('apps.authentication.urls', namespace='authentication')),
    url(r'^reportcard/', include('apps.reportcard.urls', namespace='reportcard')),
    url(r'^school/', include('apps.school.urls', namespace='school')),
    url(r'^note-assignment/', include('apps.notes.urls', namespace='note_assignment')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard'))
]

urlpatterns.append(url(r'^$', TemplateView.as_view(template_name='index.html')),)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "GRS User Admin"
admin.site.site_title = "GRS User Admin Portal"
admin.site.index_title = "GRS Site administration"

schoolmis/apps/dashboard/models.py
from django.db import models

# Create your models here.

schoolmis/apps/home/models.py
from django.db import models
from django.utils import timezone


class School(models.Model):
    name = models.CharField(max_length=250)
    address = models.CharField(max_length=300)
    pan_no = models.CharField(max_length=100)
    contact = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return "School: {}".format(self.name)


class Testimonial(models.Model):
    name = models.CharField(max_length=250)
    message = models.CharField(max_length=1500)
    image = models.FileField(upload_to='Testimonial')
    publish = models.BooleanField(default=False)

    def __str__(self):
        return "Testimonial: {}".format(self.name)


class Event(models.Model):
    title = models.CharField(max_length=250)
    day = models.DateField(u'Day of the event', help_text=u'Day of the event')
    start_time = models.TimeField(u'Starting time', help_text=u'Starting time')
    end_time = models.TimeField(u'Final time', help_text=u'Final time')
    notes = models.TextField(u'Textual Notes', help_text=u'Textual Notes', blank=True, null=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ('view_event', 'View Events'),
            ('detail_event', 'Detail Events'),

        )

    @staticmethod
    def get_status(self):
        now = timezone.now()
        date = self.day
        if now <= date:
            self.status = True  # if status is true event is upcoming
        else:
            self.status = False  # if status is false event is past
        self.save()
        return self.status


class Notice(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField(help_text="write description about notice")
    date = models.DateField(help_text="when ?")
    time = models.TimeField()

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ('view_notice', 'View Notices'),
            ('detail_notice', 'Detail Notices'),

        )


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'name:{}-email'.format(self.name, self.email)

schoolmis/apps/reportcard/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.users.models import StudentProfile, TeacherProfile
from apps.school.models import ExamType


class Subject(models.Model):
    grade = models.ForeignKey('school.grade', related_name='subject_grade')
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=50, unique=True)
    teacher = models.ForeignKey(TeacherProfile, related_name='subject_teacher', on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('view_subject', 'View Subject'),
        )

    def __str__(self):
        return "Subject:{}".format(self.name)


class Attendance(models.Model):
    created_by = models.ForeignKey(User)
    grade = models.ForeignKey('school.grade', related_name='attendance_grade')
    student = models.ManyToManyField(StudentProfile, related_name='attendance_student')
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = (
            ('view_attendance', 'View Attendance'),
            ('detail_attendance', 'Detail Attendance'),
        )

    def calculate_attendance(self):
        pass

    def get_present_students(self):
        return self.student.all()

    def get_absent_students(self):
        return set(self.grade.student_grade.all()) - set(self.student.all())

    def __str__(self):
        return "Attendance: Grade{}".format(self.grade)


class Mark(models.Model):
    created_by = models.ForeignKey(User, null=True)
    grade = models.ForeignKey('school.grade', related_name='mark_grade')
    subject = models.ForeignKey(Subject, related_name='marks_subjects')
    exam_type = models.ForeignKey(ExamType, related_name='mark_exam_type')
    full_marks = models.DecimalField(max_digits=5, decimal_places=2)
    pass_marks = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        permissions = (
            ('view_mark', 'View Marks'),
            ('detail_mark', 'Detail Marks'),

        )

    def __str__(self):
        return "Grade: {}, Subject: {}".format(self.grade, self.subject.name)


class StudentMarks(models.Model):
    mark = models.ForeignKey(Mark, on_delete=models.CASCADE, related_name='studentmarks_mark')
    student = models.ForeignKey('users.studentprofile', related_name='marks_student', on_delete=models.CASCADE)
    marks_obtained = models.DecimalField(max_digits=5, decimal_places=2)


class MarkSheet(models.Model):
    created_by = models.ForeignKey(User)
    grade = models.ForeignKey('school.grade', related_name='marksheet_grade')
    student = models.ForeignKey('users.studentprofile', related_name='marksheet_student')
    exam_type = models.ForeignKey(ExamType, related_name='marksheet_exam_type', null=True)
    issue_date = models.DateField()
    issue_by = models.ForeignKey(TeacherProfile, related_name='issue_by', on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    publish = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ('view_marksheet', 'View MarkSheet'),
            ('detail_marksheet', 'Detail MarkSheet')
        )

    def get_total_obtained_marks(self):
        return '{}'.format(sum(mark.marks_obtained for mark in self.student.marks_student.all()))

    def __str__(self):
        return "MarkSheet: {}{}".format(self.student.user.first_name, self.grade)

schoolmis/apps/dashboard/views.py
from apps.reportcard.views import MarkSheetListView, AttendanceListView
from apps.authentication.views import StudentListView, ParentListView, TeacherListView
from apps.school.views import GradeListView
from apps.home.views import EventListView, NoticeListView
from apps.notes.views import NoteListView, AssignmentListView


class Dashboard(NoteListView, AssignmentListView,  StudentListView, TeacherListView, GradeListView, EventListView,
                NoticeListView, MarkSheetListView, ParentListView, AttendanceListView):
    template_name = 'dashboard/dashboard.html'

schoolmis/apps/users/views.py
from django.shortcuts import render

# Create your views here.

schoolmis/apps/dashboard/templates/dashboard/attendance.html
 {% load filter_groups %}
         <div class="tab-pane" id="attendance">
        <div class="row">
        {% if request.user|has_group:'Teacher' %}
        <div class="col-sm-12">
        <div class="row">
<div class="col-xs-4">
        <a href="{% url 'reportcard:attendance_create' %}"><button class="btn btn-info">Add Attendance</button></a>
    </div>
    </div>
    </div>
        {% endif %}
    </div>
</div>

schoolmis/apps/dashboard/templates/dashboard/events.html
                <div class="tab-pane" id="events">
                  <div class="row">
                    {% if perms.home.add_event %}
                    <div class="col-sm-2">
                    <a href="{% url 'home:event_create' %}"><button class="btn btn-info">Add Events</button></a>
                    </div>
                   <!--  <div class="col-xs-4">
                                <a href="{% url 'note_assignment:assignment_list' %}"><button type="button" class="btn bg-purple-300 btn-block btn-float btn-float-lg">
                                    <i class="fa fa-book"></i><br><span>
                                    Add Events</span></button></a>
                            </div> -->
                        {% endif %}
                     <!-- <div class="col-sm-3">
                    <a href="{% url 'home:event_list' %}"><button class="btn btn-info">View Events</button></a>
                    </div> -->
                    {% if perms.home.add_notice %}
                         <div class="col-sm-6">
                    <a href="{% url 'home:notice_create' %}"><button class="btn btn-info pull-right">Add Notices</button></a>
                    </div>
                                    
                            {% endif %}
                    <!-- div class="col-sm-3">
                    <a href="{% url 'home:notice_list' %}"><button class="btn btn-info">View Notices</button></a>
                    </div> -->
                        </div>

                    <!-- Events: {% include 'home/event_list.html'%}<br>
                    Notice: {% include 'home/notice_list.html'%} -->
                        <div class="row">
                        <div class="col-md-12">
                            <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                                
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.js"></script>


                       <div id="calendar"></div>
                      <script type="text/javascript">
                      


        $('#calendar').fullCalendar({
  defaultView: 'agendaWeek',
             
        });
        



 

</script>
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                        <div class="col-md-12">
                            <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                                
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12">
                                {% include 'home/notice_list.html' %}
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
                        </div>

                    

schoolmis/apps/dashboard/templates/dashboard/notes.html
{% load filter_groups %}
 </style>
 <div class="tab-pane" id="notes">
  <div class="row">
    {% if perms.notes.add_assignment %}
        <div class="col-xs-2">
                <a href="{% url 'note_assignment:assignment_create' %}"><button class="btn btn-info">Add Assignment</button></a>
            </div>
            {% endif %}
               <!--  {% if perms.notes.view_assignment %}
                <div class="col-xs-3">
                <a href="{% url 'note_assignment:assignment_list' %}"><button class="btn btn-info">View Assignment</button></a>
            </div>
            {% endif %} -->
            {% if perms.notes.add_note %}    
            <div class="col-xs-6">
                <a href="{% url 'note_assignment:note_create' %}"><button class="btn btn-info pull-right">Add Notes</button></a>
            </div>
            {% endif %}
        </div>

                  <div class="row">
                        <div class="col-md-12">
                            <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                               
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12">
                                {% include 'notes/assignment_list.html' %}
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                        <div class="col-md-12">
                            <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                                
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12">
                                {% include 'notes/note_list.html' %}
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
</div>

schoolmis/apps/dashboard/templates/dashboard/reportcard.html
 {% load filter_groups %}
<div class="tab-pane" id="reportcard">
                {% if request.user|has_group:"Guardian" %}
                {% include 'reportcard/marksheet_list.html' %}
                {% endif %}
                  <div class="row">
                        {% if perms.reportcard.add_marksheet %}
                        <div class="col-xs-4">
                                <a href="{% url 'reportcard:marksheet_create' %}"><button class="btn btn-info">
                                    Create Marksheet</button></a>
                            {% endif %}
                            {% if perms.reportcard.add_mark %}
                            </div>
                            <div class="col-xs-4">
                                <a href="{% url 'reportcard:mark_create' %}"><button class="btn btn-info">
                                    Add Mark</button></a>
                            </div>
                            {% endif %}
                        </div><br>
                        <div class="row">
                        <div class="col-md-12">
                            <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12">
                               <div class="col-md-12">
    <div class="card card-plain">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Marksheet List</h4>

        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                {% if marksheet %}
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Grade</th>
                    <th>Exam Type</th>
                    <th></th>
                    <th></th>
                </thead>
                {% endif %}
                {% for marksheet in marksheet %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    {% if perms.reportcard.view_marksheet %}
                    <td><a href="{% url 'reportcard:marksheet_detail' marksheet.pk %}" class="marksheet">{{marksheet.student}}
                    </a></td>
                    {% endif %}
                    <td>{{marksheet.grade}}</td>
                    <td>{{ marksheet.exam_type }}</td>
                     {% if perms.reportcard.change_marksheet %}
                    <td><a href="{% url 'reportcard:marksheet_update' marksheet.pk %}" class="marksheets" title="Edit"><i class="fa fa-edit " aria-hidden="true"></a</td>
                    <td><a href="{% url 'reportcard:marksheet_delete' marksheet.pk %}" class="marksheets" title="Delete" ><i class="fa fa-trash-o" aria-hidden="true"></a></td>
                     {% endif %}
                     {% empty %}
                        Sorry, no Marksheet found
                    {% endfor %}
                </tr>
                  </tbody>
                      </table>
            </div>
        </div>
    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
            </div>

schoolmis/apps/dashboard/templates/dashboard/usercreate.html
{% load filter_groups %}
{% if request.user|has_group:"Admin Assistant" or request.user|has_group:"Principal" %}
<div class="active tab-pane" id="usercreate">
<div class="row">
<div class="col-sm-4">
<a href="{% url 'authentication:student_create' %}"><button class="btn btn-info">Create Student Profile</button></a>
    <br>Total Students : {{students.count}}

</div>
<div class="col-sm-4">
<a href="{% url 'authentication:teacher_create' %}"><button class="btn btn-info">Create Teacher Profile</button></a>

</div>
<div class="col-sm-4">
<a href="{% url 'authentication:parent_create' %}"><button class="btn btn-info">Create Parent Profile</button></a>
</div>
</div>
<br>
<div class="row">
<div class="col-md-12">
        <div class="panel border-left-xlg border-left-info invoice-grid timeline-content" data-background-color="purple">
        <div class="panel-footer">
            <ul>
                
                    <h4 class="subject">Teacher List</h4> Total Teachers: {{teacher.count}}
                <a href = "{% url 'authentication:export-teacher' %}" title="Export to excel"> <i class="fa fa-download fa-2x" aria-hidden="true" style="float: right; color:purple;margin-top: -32px;"></i></a>
               
            </ul>
        </div>
<div class="panel-body">
    <div class="row">
        <div class="col-sm-12">
             <div class="card-content table-responsive">
                        <table class="table table-hover">
                            {% if teacher %}
                            <thead>
                                <th>ID</th>
                                <th>First Name </th>
                                <th>last Name </th>
                                <th>Qualification</th>
                            </thead>
                            {% endif %}
                            {% for teacher in teacher %}
                            <tr>                            
                                <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'authentication:teacher_update' teacher.slug %}" class="marksheet">{{teacher.first_name}} </a></td>
                            <td> <a href="{% url 'authentication:teacher_update' teacher.slug %}" class="marksheet">{{teacher.last_name}} </a></td>
                            <td>  {{teacher.education}}</td> 
                            {% empty %}
                            Sorry No teacher found
                            </tr>
                            {% endfor %} 
                                  </table>
                        </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
{% endif %}
 