schoolmis/apps/home/api/urls.py
from django.conf.urls import url
from apps.home.api import views

urlpatterns = [
    url(r'^testimonial-list/$', views.TestimonialListApiView.as_view(),
        name='testimonial_list'),
    url(r'^school-list/$', views.SchoolListApiView.as_view(), name='school_list'),
    url(r'^event-list/$', views.EventListApiView.as_view(),
        name='testimonial_list'),
    url(r'^notice-list/$', views.NoticeListApiView.as_view(), name='school_list'),
    url(r'^contact/$', views.ContactPostApiView.as_view(), name='contact'),
]

schoolmis/apps/home/urls.py
from django.conf.urls import url, include

from apps.home import views
urlpatterns = [
    url(r'^school-create/$', views.SchoolCreateView.as_view(), name='school_create'),
    url(r'^school-list/$', views.SchoolListView.as_view(), name='school_list'),
    url(r'^school-update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='school_update'),
    url(r'^school-delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='school_delete'),

    url(r'^testimonial-create/$', views.TestimonialCreateView.as_view(), name='testimonial_create'),
    url(r'^testimonial-list/$', views.TestimonialListView.as_view(), name='testimonial_list'),
    url(r'^testimonial-update/(?P<pk>\d+)/$', views.TestimonialUpdateView.as_view(), name='testimonial_update'),
    url(r'^testimonial-delete/(?P<pk>\d+)/$', views.TestimonialDeleteView.as_view(), name='testimonial_delete'),

    url(r'^event-create/$', views.EventCreateView.as_view(), name='event_create'),
    url(r'^event-list/$', views.EventListView.as_view(), name='event_list'),
    url(r'^event-detail/(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event_detail'),
    url(r'^event-update/(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='event_update'),
    url(r'^event-delete/(?P<pk>\d+)/$', views.EventDeleteView.as_view(), name='event_delete'),

    url(r'^notice-create/$', views.NoticeCreateView.as_view(), name='notice_create'),
    url(r'^notice-list/$', views.NoticeListView.as_view(), name='notice_list'),
    url(r'^notice-detail/(?P<pk>\d+)/$', views.NoticeDetailView.as_view(), name='notice_detail'),
    url(r'^notice-update/(?P<pk>\d+)/$', views.NoticeUpdateView.as_view(), name='notice_update'),
    url(r'^notice-delete/(?P<pk>\d+)/$', views.NoticeDeleteView.as_view(), name='notice_delete'),

]

schoolmis/apps/school/urls.py
from django.conf.urls import url
from apps.school import views

urlpatterns = [

    url(r'^grade-create/$', views.GradeSubjectSectionCreateView.as_view(), name='grade_create'),
    url(r'^grade-list/$', views.GradeListView.as_view(), name='grade_list'),
    url(r'^grade-update/(?P<slug>[\w-]+)/$', views.GradeSubjectSectionUpdateView.as_view(), name='grade_update'),
    url(r'^grade-detail/(?P<slug>[\w-]+)/$', views.GradeDetailView.as_view(), name='grade_detail'),
    url(r'^grade-delete/(?P<slug>[\w-]+)/$', views.GradeDeleteView.as_view(), name='grade_delete'),

    url(r'^exam-type-create/$', views.ExamTypeCreateView.as_view(), name='exam_type_create'),
    url(r'^exam-type-list/$', views.ExamTypeListView.as_view(), name='exam_type_list'),
    url(r'^exam-type-update/(?P<pk>\d+)/$', views.ExamTypeUpdateView.as_view(), name='exam_type_update'),
    url(r'^exam-type-delete/(?P<pk>\d+)/$', views.ExamTypeDeleteView.as_view(), name='exam_type_delete'),

]

schoolmis/schoolmis/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^api/home/', include('apps.home.api.urls', namespace='home-api')),
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('apps.authentication.urls', namespace='authentication')),
    url(r'^reportcard/', include('apps.reportcard.urls', namespace='reportcard')),
    url(r'^school/', include('apps.school.urls', namespace='school')),
    url(r'^note-assignment/', include('apps.notes.urls', namespace='note_assignment')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard'))
]

urlpatterns.append(url(r'^$', TemplateView.as_view(template_name='index.html')),)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "GRS User Admin"
admin.site.site_title = "GRS User Admin Portal"
admin.site.index_title = "GRS Site administration"

schoolmis/apps/home/models.py
from django.db import models
from django.utils import timezone


class School(models.Model):
    name = models.CharField(max_length=250)
    address = models.CharField(max_length=300)
    pan_no = models.CharField(max_length=100)
    contact = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return "School: {}".format(self.name)


class Testimonial(models.Model):
    name = models.CharField(max_length=250)
    message = models.CharField(max_length=1500)
    image = models.FileField(upload_to='Testimonial')
    publish = models.BooleanField(default=False)

    def __str__(self):
        return "Testimonial: {}".format(self.name)


class Event(models.Model):
    title = models.CharField(max_length=250)
    day = models.DateField(u'Day of the event', help_text=u'Day of the event')
    start_time = models.TimeField(u'Starting time', help_text=u'Starting time')
    end_time = models.TimeField(u'Final time', help_text=u'Final time')
    notes = models.TextField(u'Textual Notes', help_text=u'Textual Notes', blank=True, null=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ('view_event', 'View Events'),
            ('detail_event', 'Detail Events'),

        )

    @staticmethod
    def get_status(self):
        now = timezone.now()
        date = self.day
        if now <= date:
            self.status = True  # if status is true event is upcoming
        else:
            self.status = False  # if status is false event is past
        self.save()
        return self.status


class Notice(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField(help_text="write description about notice")
    date = models.DateField(help_text="when ?")
    time = models.TimeField()

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ('view_notice', 'View Notices'),
            ('detail_notice', 'Detail Notices'),

        )


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'name:{}-email'.format(self.name, self.email)

schoolmis/apps/home/forms.py
from django import forms

from .models import School, Testimonial, Event, Notice


class SchoolForm(forms.ModelForm):

    class Meta:
        model = School
        fields = '__all__'


class TestimonialForm(forms.ModelForm):

    class Meta:
        model = Testimonial
        fields = '__all__'


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = '__all__'


class NoticeForm(forms.ModelForm):

    class Meta:
        model = Notice
        fields = '__all__'

schoolmis/apps/school/forms.py
from django import forms
from django.forms import inlineformset_factory

from apps.reportcard.models import Subject
from .models import Section, Grade, ExamType


class GradeSubjectForm(forms.ModelForm):

    class Meta:
        model = Subject
        fields = '__all__'


class GradeSectionForm(forms.ModelForm):
    class Meta:
        model = Section
        exclude = ()


GradeSectionFormSet = inlineformset_factory(Grade, Section,
                                            form=GradeSectionForm, extra=1)

GradeSubjectFormSet = inlineformset_factory(Grade, Subject,
                                            form=GradeSubjectForm, extra=1)


class ExamTypeForm(forms.ModelForm):

    class Meta:
        model = ExamType
        fields = '__all__'

schoolmis/apps/home/api/views.py
from rest_framework.generics import (ListAPIView, CreateAPIView)

from .serializers import (
    TestimonialSerializers, SchoolSerializers, EventSerializers, NoticeSerializers, ContactSerializers)
from apps.home.models import (School, Testimonial, Event, Notice, Contact)


class TestimonialListApiView(ListAPIView):
    queryset = Testimonial.objects.filter(publish=True)
    serializer_class = TestimonialSerializers


class SchoolListApiView(ListAPIView):
    queryset = School.objects.all()
    serializer_class = SchoolSerializers


class EventListApiView(ListAPIView):
    queryset = Event.objects.all()
    serializer_class = EventSerializers


class NoticeListApiView(ListAPIView):
    queryset = Notice.objects.all()
    serializer_class = NoticeSerializers


class ContactPostApiView(CreateAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializers

schoolmis/apps/home/views.py
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView, DetailView

from apps.userrole import permissions
from .mixins import SchoolMixin, TestimonialMixin, EventMixin, NoticeMixin
from .models import Event, Notice


class HomeView(TemplateView):
    template_name = 'home/home.html'


class SchoolCreateView(permissions.CheckPermissionListMixin,SchoolMixin, CreateView):
    template_name = 'home/school_form.html'


class SchoolListView(TestimonialMixin, ListView):
    template_name = 'home/school_list.html'


class SchoolUpdateView(permissions.CheckPermissionUpdateMixin, SchoolMixin, UpdateView):
    template_name = 'home/school_update.html'


class SchoolDeleteView(permissions.CheckPermissionDeleteMixin, SchoolMixin, DeleteView):
    template_name = 'home/school_delete.html'


class TestimonialCreateView(permissions.CheckPermissionListMixin,TestimonialMixin, CreateView):
    template_name = 'home/testimonial_form.html'


class TestimonialListView(TestimonialMixin, ListView):
    template_name = 'home/testimonial_list.html'


class TestimonialUpdateView(permissions.CheckPermissionUpdateMixin, TestimonialMixin, UpdateView):
    template_name = 'home/testimonial_update.html'


class TestimonialDeleteView(permissions.CheckPermissionDeleteMixin, TestimonialMixin, DeleteView):
    template_name = 'home/testimonial_delete.html'


class EventCreateView(permissions.CheckPermissionCreateMixin, EventMixin, CreateView):
    pass


class EventListView(EventMixin, ListView):

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['events'] = Event.objects.all()
            return context
        except:
            pass


class EventDetailView(EventMixin, DetailView):
    pass


class EventUpdateView(permissions.CheckPermissionUpdateMixin, EventMixin, UpdateView):
    pass


class EventDeleteView(permissions.CheckPermissionDeleteMixin, EventMixin, DeleteView):
    template_name = 'home/event_delete.html'


class NoticeCreateView(permissions.CheckPermissionCreateMixin, NoticeMixin, CreateView):
    pass


class NoticeListView(NoticeMixin, ListView):

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['notices'] = Notice.objects.all()
            return context
        except:
            pass


class NoticeDetailView(NoticeMixin, DetailView):
    pass


class NoticeUpdateView(permissions.CheckPermissionUpdateMixin, NoticeMixin, UpdateView):
    pass


class NoticeDeleteView(permissions.CheckPermissionDeleteMixin, NoticeMixin, DeleteView):
    template_name = 'home/notice_delete.html'

schoolmis/apps/school/views.py
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.db import transaction
from django.core.exceptions import PermissionDenied
from django.http import Http404

from apps.userrole.permissions import CheckPermissionCreateMixin, CheckPermissionListMixin, CheckPermissionUpdateMixin, \
    CheckPermissionDeleteMixin, CheckPermissionDetailMixin
from .forms import GradeSectionFormSet, GradeSubjectFormSet, ExamTypeForm
from .mixins import GradeMixin, ExamTypeMixin
from .models import Grade


class GradeSubjectSectionCreateView(GradeMixin, CheckPermissionCreateMixin, CreateView):

    def get_context_data(self, **kwargs):
        data = super(GradeSubjectSectionCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['grade_section'] = GradeSectionFormSet(self.request.POST)
            data['grade_subject'] = GradeSubjectFormSet(self.request.POST)

        else:
            data['grade_section'] = GradeSectionFormSet()
            data['grade_subject'] = GradeSubjectFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        grade_section = context['grade_section']
        grade_subject = context['grade_subject']

        with transaction.atomic():
            self.object = form.save()
            if grade_section.is_valid() and grade_subject.is_valid():
                grade_section.instance = self.object
                grade_subject.instance = self.object
                grade_section.save()
                grade_subject.save()
        return super(GradeSubjectSectionCreateView, self).form_valid(form)


class GradeListView(CheckPermissionListMixin, GradeMixin, ListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.groups.filter(name='Student'):
            context['grade'] = Grade.objects.filter(name=self.request.user.student_profile.grade)
            return context
        elif self.request.user.groups.filter(name='Admin Assistant') | self.request.user.groups.filter(name='Principal'):
            try:
                context['grade'] = Grade.objects.all()
                return context
            except TypeError:
                pass
        elif self.request.user.groups.filter(name='Teacher'):
            try:
                context['grade'] = Grade.objects.filter(name__in=self.request.user.teacher_profile.subject_teacher.
                                                        values('grade__name'))
                return context
            except TypeError:
                pass

        else:
            context['grade'] = None
            return context


class GradeDetailView(CheckPermissionDetailMixin, GradeMixin, DetailView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.groups.filter(name='Student'):
            try:
                grade = Grade.objects.filter(name=self.request.user.student_profile.grade)
                context['grade'] = self.get_object(grade)
                return context
            except Http404:
                raise PermissionDenied
        elif self.request.user.groups.filter(name='Teacher'):
            try:
                grade = Grade.objects.filter(
                    name__in=self.request.user.teacher_profile.subject_teacher.values('grade__name'))
                context['grade'] = self.get_object(grade)

                return context
            except TypeError:
                pass
        elif self.request.user.groups.filter(name='Admin Assistant') or self.request.user.groups.filter(
                name='Principal'):
            context['grade'] = self.get_object()
            return context
        else:
            context['grade'] = None
            return context


class GradeSubjectSectionUpdateView(GradeMixin, CheckPermissionUpdateMixin, UpdateView):

    def get_context_data(self, **kwargs):
        data = super(GradeSubjectSectionUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['grade_section'] = GradeSectionFormSet(self.request.POST, instance=self.object)
            data['grade_subject'] = GradeSubjectFormSet(self.request.POST, instance=self.object)

        else:
            data['grade_section'] = GradeSectionFormSet(instance=self.object)
            data['grade_subject'] = GradeSubjectFormSet(instance=self.object)

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        grade_section = context['grade_section']
        grade_subject = context['grade_subject']

        with transaction.atomic():
            self.object = form.save()

            if grade_section.is_valid() and grade_subject.is_valid():
                grade_section.instance = self.object
                grade_subject.instance = self.object

                grade_section.save()
                grade_subject.save()
        return super(GradeSubjectSectionUpdateView, self).form_valid(form)


class GradeDeleteView(GradeMixin, CheckPermissionDeleteMixin, DeleteView):
    template_name = 'school/grade_delete.html'


class ExamTypeCreateView(ExamTypeMixin, CheckPermissionCreateMixin, CreateView):
    pass


class ExamTypeListView(ExamTypeMixin, CheckPermissionListMixin, ListView):
    pass


class ExamTypeUpdateView(ExamTypeMixin, CheckPermissionUpdateMixin, UpdateView):
    pass


class ExamTypeDeleteView(ExamTypeMixin, CheckPermissionDeleteMixin, DeleteView):
    template_name = 'school/examtype_delete.html'

schoolmis/apps/home/templates/home/event_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    Are you sure you want to delete {{events}}
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/home/templates/home/event_detail.html
{% load staticfiles %}
{% load filter_groups %}
{% include 'dashboard/base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
 <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
            <div class="logo">
                    GRS 
                </a>
                <span class="label bg-info">Academic Year: ( 2018 - 2019 )</span>
            </div>
            <div class="sidebar-wrapper">
                 {% include 'dashboard/sidebar/events_sidebar.html' %}
            </div>
        </div>{% include 'dashboard/navbar.html' %}
            <div class="content">           
<div class="active tab-pane" id="events">
	<div class="row">
             <div class="col-md-12">
                 <div class="panel border-left-xlg border-left-info invoice-grid timeline-content">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title">Events</h4>
                    </div>
                    <style type="text/css">
                    	p{
                    		margin-top: 10px;
                    	}
                    </style>
                    <div class="card-content table-responsive">    
						<b>Title:</b><p>{{events.title}}</p><hr>
						<b>Day Of Event:</b><p>{{events.day}}</p><hr>
						<b>Description:</b><p>{{events.notes}}</p><hr>
						<b>Start Time:</b><p>{{events.start_time}}</p><hr>
						<b>End Time:</b><p> {{events.start_time}}</p><hr>
                        </div>
                        {% if perms.home.change_event %}
                        <a href="{% url 'home:event_update' events.pk%}" class="marksheets" title="Edit"><button class="btn btn-primary pull-right">Edit
                        </button></a>
                        {% endif %}
                    </div>
                </div>
                  </div>
                    </div>
                    </div>
                    </div>
                    </div>
                </div>



</div>
</div>
</body>
<!--   Core JS Files   -->
{% include 'dashboard/dashboardjs.html' %}
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js' %}
        demo.initDashboardPageCharts();

    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

schoolmis/apps/home/templates/home/event_form.html
{% load staticfiles %}
{% load filter_groups %}
{% include 'dashboard/base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
 <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
            <div class="logo">
                    GRS 
                </a>
                <span class="label bg-info">Academic Year: ( 2018 - 2019 )</span>
            </div>
            <div class="sidebar-wrapper">
                {% include 'dashboard/sidebar/events_sidebar.html' %}
            </div>
        </div>{% include 'dashboard/navbar.html' %}
            <div class="content">           
<div class="active tab-pane" id="events">

     <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Event</h4>
                                </div>
                                <div class="card-content">
                                    {% include 'form_error.html' %}
                                   <form action="" method="post">{% csrf_token %}
                               <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_title" class="control-label">Title:</label>
                                            <input type="text" name="title" required="" maxlength="250" id="id_title" class="form-control" value="{{form.title.value|default_if_none:''}}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_day" class="control-label">EventDate:</label>
                                            <input type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="day" value="{{form.day.value|date:'n/d/Y'}}" id="id_day"  class="form-control">
                                            
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_start_time" class="control-label">Start Time:</label>
                                            <input type="text" name="start_time" required="" maxlength="250" id="id_start_time" class="form-control" 

                                        value="{{form.start_time.value|date:'H:i'}}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_end_time" class="control-label">End Time:</label>
                                            <input type="text" name="end_time" required="" maxlength="250" id="id_end_time" class="form-control" value="{{form.end_time.value|date:'H:i'}}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_notes" class="control-label">Description:</label>
                                            <input type="textarea"  name="notes" required=""  id="id_notes" class="form-control" value="{{form.notes.value|default_if_none:''}}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <label for="id_status">Status:</label>
                                <input type="checkbox" name="status" id="id_status" value="{{ form.status.value}}"><br>
                    <input type="submit" class="btn btn-primary">
                    </form>
                    </div>
                                    <!-- <input type="submit"> -->
                                </form>
                                </div>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
    </div>
            </div>
            </body>
<!--   Core JS Files   -->
{% include 'dashboard/dashboardjs.html' %}
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js' %}
        demo.initDashboardPageCharts();

    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

schoolmis/apps/home/templates/home/home.html
<p> This is homepage </p>

schoolmis/apps/home/templates/home/notice_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    Are you sure you want to delete {{notices}}
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/home/templates/home/notice_list.html
<div class="col-md-12">
    <div class="card card-plain">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Notice Lists</h4>
        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                {% if notices %}
                <thead>
                    <th>ID</th>
                    <th>Title</th>
                    <th></th>
                    <th></th>
                </thead>
                {% endif %}
				{% for notice in notices %}

                <tr>
                	<td>{{ forloop.counter }}</td>
	                <td><a href="{% url 'home:notice_detail' notice.pk%}"  class="marksheet">{{notice.title}}</a></td>
	                {% if perms.home.change_notice %}
	                 
	                <td><a href="{% url 'home:notice_update' notice.pk%}" class="marksheets" title="Edit"><i class="fa fa-edit " aria-hidden="true"></i></a>
					</td>
					{% endif %}
					{% if perms.home.delete_notice %}
	                <td><a href="{% url 'home:notice_delete' notice.pk%}" class="marksheets" title="Delete"><i class="fa fa-trash-o " aria-hidden="true"></i></a></td>	         
	                 {% endif %}

					
            	</tr>
            	{% empty %}
					Sorry, no Notice
					{% endfor %}
            	  </tbody>
                      </table>
            </div>
        </div>
    </div>

schoolmis/apps/home/templates/home/school_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>

schoolmis/apps/home/templates/home/school_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {% include 'form_error.html' %}
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>

schoolmis/apps/home/templates/home/school_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

schoolmis/apps/home/templates/home/school_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {% include 'form_error.html' %}
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>

schoolmis/apps/home/templates/home/testimonial_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>

schoolmis/apps/home/templates/home/testimonial_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>

schoolmis/apps/home/templates/home/testimonial_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

schoolmis/apps/home/templates/home/testimonial_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {{ form.as_p }}
    <input type="submit"/>
    {% csrf_token %}
</form>
</body>
</html>