schoolmis/apps/notes/urls.py
from django.conf.urls import url
from .views import (
    NoteCreateView,
    NoteListView,
    NoteDetailView,
    NoteUpdateView,
    NoteDeleteView,
    AssignmentCreateView,
    AssignmentListView,
    AssignmentDetailView,
    AssignmentUpdateView,
    AssignmentDeleteView,
    load_students_subjects,
    load_students_subjects_formset,
    load_subjects,
    load_students,



)
urlpatterns = [

    url(r'^note-create/$', NoteCreateView.as_view(), name='note_create'),
    url(r'^note-list/$', NoteListView.as_view(), name='note_list'),
    url(r'^note-detail/(?P<pk>\d+)/$', NoteDetailView.as_view(), name='note_detail'),
    url(r'^note-update/(?P<pk>\d+)/$', NoteUpdateView.as_view(), name='note_update'),
    url(r'^note-delete/(?P<pk>\d+)/$', NoteDeleteView.as_view(), name='note_delete'),

    url(r'^assignment-create/$', AssignmentCreateView.as_view(), name='assignment_create'),
    url(r'^assignment-list/$', AssignmentListView.as_view(), name='assignment_list'),
    url(r'^assignment-detail/(?P<pk>\d+)/$', AssignmentDetailView.as_view(), name='assignment_detail'),
    url(r'^assignment-update/(?P<pk>\d+)/$', AssignmentUpdateView.as_view(), name='assignment_update'),
    url(r'^assignment-delete/(?P<pk>\d+)/$', AssignmentDeleteView.as_view(), name='assignment_delete'),
    url('ajax/load-students-subjects/', load_students_subjects, name='ajax_load_students_subjects'),
    url('ajax/load-students-subjects-formset/', load_students_subjects_formset, name='ajax_load_students_subjects_formset'),
    url('ajax/load-subjects/', load_subjects, name='ajax_load_subjects'),
    url('ajax/load-students/', load_students, name='ajax_load_students'),

]

schoolmis/apps/reportcard/urls.py
from django.conf.urls import url
from .views import (
    SubjectListView,
    AttendanceCreateView,
    AttendanceListView,
    AttendanceDetailView,
    AttendanceUpdateView,
    AttendanceDeleteView,
    MarkSheetCreateView,
    MarkSheetListView,
    MarkSheetDetailView,
    MarkSheetUpdateView,
    MarkSheetDeleteView,
    MarkSheetPdfZipView,
    MarkSheetPdfView,
    StudentMarksCreateView,
    StudentMarksListView,
    StudentMarksDetailView,
    StudentMarksUpdateView,
    StudentMarksDeleteView,
    StudentAutocomplete,


)

urlpatterns = [
    url(r'^subject-list/$', SubjectListView.as_view(), name='subject_list'),

    url(r'^attendance-create/$', AttendanceCreateView.as_view(), name='attendance_create'),
    url(r'^attendance-list/$', AttendanceListView.as_view(), name='attendance_list'),
    url(r'^attendance-detail/(?P<pk>\d+)/$', AttendanceDetailView.as_view(), name='attendance_detail'),
    url(r'^attendance-update/(?P<pk>\d+)/$', AttendanceUpdateView.as_view(), name='attendance_update'),
    url(r'^attendance-delete/(?P<pk>\d+)/$', AttendanceDeleteView.as_view(), name='attendance_delete'),

    url(r'^marksheet-create/$', MarkSheetCreateView.as_view(), name='marksheet_create'),
    url(r'^marksheet-list/$', MarkSheetListView.as_view(), name='marksheet_list'),
    url(r'^marksheet-detail/(?P<pk>\d+)/$', MarkSheetDetailView.as_view(), name='marksheet_detail'),
    url(r'^marksheet-update/(?P<pk>\d+)/$', MarkSheetUpdateView.as_view(), name='marksheet_update'),
    url(r'^marksheet-delete/(?P<pk>\d+)/$', MarkSheetDeleteView.as_view(), name='marksheet_delete'),
    url(r'^marksheet-zip/$', MarkSheetPdfZipView.as_view(), name='marksheet_zip'),
    url(r'^marksheet-pdf/(?P<pk>\d+)/$', MarkSheetPdfView.as_view(), name='marksheet_pdf'),
    url(r'^student-autocomplete/$', StudentAutocomplete.as_view(), name='student_autocomplete'),

    url(r'^mark-create/$', StudentMarksCreateView.as_view(), name='mark_create'),
    url(r'^mark-list/$', StudentMarksListView.as_view(), name='mark_list'),
    url(r'^mark-detail/(?P<pk>\d+)/$', StudentMarksDetailView.as_view(), name='mark_detail'),
    url(r'^mark-update/(?P<pk>\d+)/$', StudentMarksUpdateView.as_view(), name='mark_update'),
    url(r'^mark-delete/(?P<pk>\d+)/$', StudentMarksDeleteView.as_view(), name='mark_delete'),

]

schoolmis/schoolmis/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^api/home/', include('apps.home.api.urls', namespace='home-api')),
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('apps.authentication.urls', namespace='authentication')),
    url(r'^reportcard/', include('apps.reportcard.urls', namespace='reportcard')),
    url(r'^school/', include('apps.school.urls', namespace='school')),
    url(r'^note-assignment/', include('apps.notes.urls', namespace='note_assignment')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard'))
]

urlpatterns.append(url(r'^$', TemplateView.as_view(template_name='index.html')),)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "GRS User Admin"
admin.site.site_title = "GRS User Admin Portal"
admin.site.index_title = "GRS Site administration"

schoolmis/apps/reportcard/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.users.models import StudentProfile, TeacherProfile
from apps.school.models import ExamType


class Subject(models.Model):
    grade = models.ForeignKey('school.grade', related_name='subject_grade')
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=50, unique=True)
    teacher = models.ForeignKey(TeacherProfile, related_name='subject_teacher', on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('view_subject', 'View Subject'),
        )

    def __str__(self):
        return "Subject:{}".format(self.name)


class Attendance(models.Model):
    created_by = models.ForeignKey(User)
    grade = models.ForeignKey('school.grade', related_name='attendance_grade')
    student = models.ManyToManyField(StudentProfile, related_name='attendance_student')
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = (
            ('view_attendance', 'View Attendance'),
            ('detail_attendance', 'Detail Attendance'),
        )

    def calculate_attendance(self):
        pass

    def get_present_students(self):
        return self.student.all()

    def get_absent_students(self):
        return set(self.grade.student_grade.all()) - set(self.student.all())

    def __str__(self):
        return "Attendance: Grade{}".format(self.grade)


class Mark(models.Model):
    created_by = models.ForeignKey(User, null=True)
    grade = models.ForeignKey('school.grade', related_name='mark_grade')
    subject = models.ForeignKey(Subject, related_name='marks_subjects')
    exam_type = models.ForeignKey(ExamType, related_name='mark_exam_type')
    full_marks = models.DecimalField(max_digits=5, decimal_places=2)
    pass_marks = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        permissions = (
            ('view_mark', 'View Marks'),
            ('detail_mark', 'Detail Marks'),

        )

    def __str__(self):
        return "Grade: {}, Subject: {}".format(self.grade, self.subject.name)


class StudentMarks(models.Model):
    mark = models.ForeignKey(Mark, on_delete=models.CASCADE, related_name='studentmarks_mark')
    student = models.ForeignKey('users.studentprofile', related_name='marks_student', on_delete=models.CASCADE)
    marks_obtained = models.DecimalField(max_digits=5, decimal_places=2)


class MarkSheet(models.Model):
    created_by = models.ForeignKey(User)
    grade = models.ForeignKey('school.grade', related_name='marksheet_grade')
    student = models.ForeignKey('users.studentprofile', related_name='marksheet_student')
    exam_type = models.ForeignKey(ExamType, related_name='marksheet_exam_type', null=True)
    issue_date = models.DateField()
    issue_by = models.ForeignKey(TeacherProfile, related_name='issue_by', on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    publish = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ('view_marksheet', 'View MarkSheet'),
            ('detail_marksheet', 'Detail MarkSheet')
        )

    def get_total_obtained_marks(self):
        return '{}'.format(sum(mark.marks_obtained for mark in self.student.marks_student.all()))

    def __str__(self):
        return "MarkSheet: {}{}".format(self.student.user.first_name, self.grade)

schoolmis/apps/reportcard/forms.py
from django import forms
from django.forms import inlineformset_factory

from dal import autocomplete
from decimal import Decimal

from apps.school.models import Grade
from apps.users.models import StudentProfile
from .models import Subject, Attendance, MarkSheet, Mark, StudentMarks


class AttendanceForm(forms.ModelForm):

    class Meta:
        model = Attendance
        exclude = ('created_by', 'slug',)

        widgets = {
            'student': forms.CheckboxSelectMultiple()
        }

        student = forms.ModelMultipleChoiceField(queryset=StudentProfile.objects.all(), required=False)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['grade'].queryset = Grade.objects.filter(name__in=user.teacher_profile.class_teacher.values('grade__name'))
        self.fields['student'].queryset = StudentProfile.objects.none()

        if 'grade' in self.data:
            try:
                grade_id = int(self.data.get('grade'))
                self.fields['student'].queryset = StudentProfile.objects.filter(grade_id=grade_id)

            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty student queryset
        elif self.instance.pk:
            self.fields['student'].queryset = self.instance.grade.student_grade


class MarkSheetForm(forms.ModelForm):

    class Meta:
        model = MarkSheet
        fields = ('grade', 'student', 'exam_type', 'issue_by', 'issue_date', 'publish')
        widgets = {
            'student': autocomplete.ModelSelect2(url='reportcard:student_autocomplete', forward=['grade'])
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['grade'].queryset = Grade.objects.filter(name__in=user.teacher_profile.class_teacher.
                                                             values('grade__name'))
        self.fields['student'].queryset = StudentProfile.objects.none()

        if 'grade' in self.data:
            try:
                grade_id = int(self.data.get('grade'))
                self.fields['student'].queryset = StudentProfile.objects.filter(grade_id=grade_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty student queryset
        elif self.instance.pk:
            self.fields['student'].queryset = self.instance.grade.student_grade


class StudentMarksForm(forms.ModelForm):

    class Meta:
        model = StudentMarks
        fields = '__all__'

    # def clean_marks_obtained(self):
    #     full_marks = self.data.get('full_marks')
    #     marks_obtained = self.cleaned_data['marks_obtained']
    #     if marks_obtained > Decimal(full_marks):
    #         raise forms.ValidationError('Marks obtained must not be greater than Full marks')


StudentMarksFormSet = inlineformset_factory(Mark, StudentMarks,
                                            form=StudentMarksForm, extra=0)


class MarkForm(forms.ModelForm):

    class Meta:
        model = Mark
        exclude = ('created_by',)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['grade'].queryset = Grade.objects.filter(name__in=user.teacher_profile.subject_teacher.
                                                             values('grade__name'))
        self.fields['subject'].queryset = Subject.objects.none()

        if 'grade' in self.data:
            try:
                grade_id = int(self.data.get('grade'))
                self.fields['subject'].queryset = Subject.objects.filter(
                        grade_id=grade_id, teacher=user.teacher_profile)

            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty student queryset
        elif self.instance.pk:
            self.fields['subject'].queryset = self.instance.grade.subject_grade

    def clean_pass_marks(self):
        pass_marks = self.cleaned_data['pass_marks']
        full_marks = Decimal(self.data.get('full_marks'))
        if pass_marks >= full_marks:
            raise forms.ValidationError('Pass marks must be less than full marks')
        return pass_marks

schoolmis/apps/reportcard/templates/reportcard/attendance_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Attendance Delete
<form action="" method="post">{% csrf_token %}
    Are you sure you want to delete {{attendance}}
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/reportcard/templates/reportcard/attendance_list.html
{% load filter_groups %}
<!DOCTYPE html>
<a lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<br>
{% if request.user|has_group:"Teacher" or request.user|has_group:"Admin Assistant" or request.user|has_group:"Principal" %}

{% for attendance in attendance %}

     <a href={% url 'reportcard:attendance_detail' attendance.pk %} class="marksheet"><br>
       {{forloop.counter}}.&nbsp; <span style="color:#000;"> Grade {{ attendance.grade }}, {{ attendance.date }}</span>
     </a>

    {% if perms.reportcard.change_attendance %}
        <a href="{% url 'reportcard:attendance_update' attendance.pk %}" title="Edit" class="marksheet" style="margin-left: 300px;"><i class="fa fa-edit " aria-hidden="true"></i></a>
        <a href={% url 'reportcard:attendance_delete' attendance.pk %} title="Delete" class="marksheet" style="float: right;" ><i class="fa fa-trash-o " aria-hidden="true"></i></a> <br>
     <a href="{% url 'reportcard:attendance_detail' attendance.pk %}" >
        <span style="color:#000;"> Grade {{ attendance.grade }}, {{ attendance.date }}</span>
     </a>
    {% endif %}
    {% empty %}
    Sorry, no Attendance
{% endfor %}
    {% else %}
    You are not allowed...
{% endif %}



</body>
</html>

schoolmis/apps/reportcard/templates/reportcard/mark_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    Are you sure you want to delete {{mark}}
    <input type="submit">
</form>
</body>
</html>

schoolmis/apps/reportcard/templates/reportcard/mark_list.html
{% for mark in mark %}
    <a href="{% url 'reportcard:mark_detail' mark.pk %}">{{mark}}</a>
    	 {% if perms.reportcard.change_mark %}
    <a href="{% url 'reportcard:mark_update' mark.pk %}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                <a href="{% url 'reportcard:mark_delete' mark.pk %}"><i class="fa fa-trash-o " aria-hidden="true"></i></a> <br>
                {% endif %}
{% empty %}
    Sorry, no Mark found
{% endfor %}
     

schoolmis/apps/reportcard/templates/reportcard/marksheet_form.html
{% load staticfiles %}
{% load filter_groups %}
{% include 'dashboard/base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
 <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
            <div class="logo">
                    GRS 
                </a>
                <span class="label bg-info">Academic Year: ( 2018 - 2019 )</span>
            </div>
            <div class="sidebar-wrapper">
                {% include 'dashboard/sidebar/marksheet_sidebar.html' %}
            </div>
        </div>{% include 'dashboard/navbar.html' %}
        <div class="content"> 
         <div class="active tab-pane" id="reportcard">
     <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Reportcard</h4>
                                </div>
                                <div class="card-content">
                                    {% include 'form_error.html' %}
                                <form action="" method="post" id="marksheet_form" data-form-url="{% url 'note_assignment:ajax_load_students' %}">{% csrf_token %}
                               <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_grade" class="control-label">Grade:</label>
                                            {{form.grade }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                             <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_student" class="control-label">Student:</label>
                                            {{form.student}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_exam_type" class="control-label">Exam Type:</label>
                                            {{form.exam_type}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_issue_by" class="control-label">Issued By:</label>
                                            {{form.issue_by}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_issue_date" class="control-label">Issue Date:</label>
                                            {{form.issue_date}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_publish" class="control-label">Publish:</label>
                                            {{form.publish}}
                                            </div>
                                        </div>
                                    </div>
                            </div>  
                    <input type="submit" class="btn btn-primary">
                    </form>
                    </div> 
                     </div>
                    </div>
                    </div> 
                    </div>
                </div>
            </div>          
       
<script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}

  <script>
    $("#id_grade").change(function () {
      var url = $("#marksheet_form").attr("data-form-url");
      var grade = $(this).val();
      $.ajax({
        url: url,
        data: {
          'grade': grade
        },
        success: function (data) {
         $("#id_student").html(data);

        }

      });

    });
  </script>
<!--   Core JS Files   -->
{% include 'dashboard/dashboardjs.html' %}
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js' %}
        demo.initDashboardPageCharts();

    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

schoolmis/apps/reportcard/templates/reportcard/marksheet_list.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{#<div class="col-md-12">#}
{#    <div class="card card-plain">#}
{#        <div class="card-header" data-background-color="purple">#}
{#            <h4 class="title">Marksheet List</h4>#}
{#        </div>#}
{#        <div class="card-content table-responsive">#}
{#            <table class="table table-hover">#}
{#                <thead>#}
{#                    <th>ID</th>#}
{#                    <th>Name</th>#}
{#                    <th>Grade</th>#}
{#                </thead>#}
{#                {% for marksheet in marksheet %}#}
{#                <tr>#}
{#	                <td>{{ forloop.counter }}</td>#}
{#	                {% if perms.reportcard.view_marksheet %}#}
{#	                <td><a href="{% url 'reportcard:marksheet_detail' marksheet.pk %}" class="marksheet">{{marksheet.student}}#}
{# 					</a></td>#}
{#	                {% endif %}#}
{#	                <td>{{marksheet.grade}}</td>#}
{#	                 {% if perms.reportcard.change_marksheet %}#}
{#	                <td><a href="{% url 'reportcard:marksheet_delete' marksheet.pk %}" class="marksheets" ><i class="fa fa-trash-o " aria-hidden="true"></i></a></td>#}
{#	                <td><a href="{% url 'reportcard:marksheet_update' marksheet.pk %}" class="marksheets" style="margin-right: 30px;"><i class="fa fa-edit " aria-hidden="true"></i></a>&nbsp;&nbsp;<br></td>#}
{#	                 {% endif %}#}
{#	                 {% empty %}#}
{#					    Sorry, no Marksheet found#}
{#					{% endfor %}#}
{#            	</tr>#}
{#            	  </tbody>#}
{#                      </table>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{##}
{#</body>#}
{#</html>#}

schoolmis/apps/reportcard/templates/reportcard/marksheet_update.html
{% load staticfiles %}
{% load filter_groups %}
{% include 'dashboard/base.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
 <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
            <div class="logo">
                    GRS 
                </a>
                <span class="label bg-info">Academic Year: ( 2018 - 2019 )</span>
            </div>
            <div class="sidebar-wrapper">
                {% include 'dashboard/sidebar/marksheet_sidebar.html' %}
            </div>
        </div>{% include 'dashboard/navbar.html' %}
        <div class="content"> 
         <div class="active tab-pane" id="attendance">
     <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Reportcard</h4>
                                </div>
                                <div class="card-content">
                                    {% include 'form_error.html' %}
                                <form action="" method="post" id="marksheet_form" data-form-url="{% url 'note_assignment:ajax_load_students' %}">{% csrf_token %}
                               <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_grade" class="control-label">Grade:</label>
                                            {{form.grade }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_student" class="control-label">Student:</label>
                                            {{form.student}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                             <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_exam_type" class="control-label">Exam Type:</label>
                                            {{form.exam_type}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_issue_by" class="control-label">Issued By:</label>
                                            {{form.issue_by}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_issue_date" class="control-label">Issue Date:</label>
                                            {{form.issue_date}}
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="form-group label-floating">
                                            <label for="id_publish" class="control-label">Publish:</label>
                                            {{form.publish}}
                                            </div>
                                        </div>
                                    </div>
                            </div>  
                    <input type="submit" class="btn btn-primary">
                    </form>
                    </div> 
                     </div>
                    </div>
                    </div> 
                    </div>
                </div>
            </div>          
       
<script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}

  <script>
    $("#id_grade").change(function () {
      var url = $("#marksheet_form").attr("data-form-url");
      var grade = $(this).val();
      $.ajax({
        url: url,
        data: {
          'grade': grade
        },
        success: function (data) {
         $("#id_student").html(data);

        }

      });

    });
  </script>
<!--   Core JS Files   -->
{% include 'dashboard/dashboardjs.html' %}
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js' %}
        demo.initDashboardPageCharts();

    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</html>

schoolmis/apps/reportcard/templates/reportcard/marksheet_zip.html
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Marsheet- {{marksheet.student.user}}</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'/>
</head>
<body>
<div>
        <div style="text-align: center; margin-top: 20px">
         <form action="{% url 'reportcard:marksheet_pdf' marksheet.pk %}" method="post">{% csrf_token %}
         <input type="submit" value="Export as PDF" style="text-align: center">
         </form>
        </div>
    <center>
        <div>
            Student Name: {{marksheet.student.user}}<br>
            Grade: {{marksheet.grade.name }}<br>
            Section: {{marksheet.student.section.name }}<br>
        </div>
    </center>
<div class="table-responsive">
<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col" rowspan="2">#</th>
      <th scope="col" rowspan="2">Subject</th>
      <th scope="col" rowspan="2">Full</th>
      <th scope="col" rowspan="2">Pass</th>
      <th scope="col" colspan="2"><center>Obtained Marks</center></th>
      <th scope="col" rowspan="2">Total</th>
      <th scope="col" rowspan="2">Remarks</th>
    </tr>
    <tr>
      <th scope="col">TH</th>
      <th scope="col">PR</th>
    </tr>
  </thead>
  <tbody>
  {% for marksheet in marksheet.student.marks_student.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{marksheet.mark.subject.name }}</td>
      <td>{{marksheet.mark.full_marks}}</td>
      <td>{{marksheet.mark.pass_marks}}</td>
      <td>{{marksheet.marks_obtained}}</td>
      <td>20</td>
      <td>Total: </td>
      <td>Pass</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
    <b>Issue by</b> :{{marksheet.issue_by}}<br>
    <b>Total marks obtained </b>: {{marksheet.get_total_obtained_marks}}

</div>
</div>
</body>

</html>